export * from './instances.table';
export * from './messages.table';
export * from './message-status-updates.table';
export * from './contacts.table';
export * from './chats.table';
export * from './media-files.table';
export * from './templates.table';
export * from './webhook-configs.table';
export * from './instance-settings.table';
